using System.Text;
using AQ.Denials.Ingest;

namespace AQ.Denials.Api.Reports;

/// <summary>
/// Generates the reconciliation markdown without starting the web host.
/// </summary>
/// <remarks>
/// <para>
/// <c>--report</c> exists so the deliverable can be regenerated on a machine with no Postgres and
/// no network: it reads <c>DATA_DIR</c>, runs the same pipeline the API runs, and prints the same
/// markdown the <c>/api/reconciliation/report.md</c> endpoint returns. Two code paths producing the
/// same document would be two documents; this calls the identical method.
/// </para>
/// <para>
/// Usage: <c>dotnet run --project src/AQ.Denials.Api -- --report [--out path]</c>
/// </para>
/// </remarks>
public static class Report
{
    public static void Write(string[] args)
    {
        var dataDir = Environment.GetEnvironmentVariable("DATA_DIR");

        string? requested = null;
        for (var i = 0; i < args.Length - 1; i++)
            if (args[i] == "--out") requested = args[i + 1];

        // A relative --out is resolved against the repository root, not against whatever
        // directory the host process happens to have been started in (`dotnet run` starts the
        // app in the project folder), so `--out docs/report.md` means the same thing always.
        var outputPath = requested is null
            ? DefaultOutputPath()
            : Path.IsPathRooted(requested)
                ? requested
                : Path.Combine(FindRepositoryRoot() ?? Directory.GetCurrentDirectory(), requested);

        var outcome = IngestPipeline.Run(DataPack.Read(dataDir));
        var markdown = Render(outcome);

        if (outputPath is not null)
        {
            var directory = Path.GetDirectoryName(Path.GetFullPath(outputPath));
            if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);
            File.WriteAllText(outputPath, markdown, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            Console.WriteLine($"wrote {outputPath}");
        }
        else
        {
            Console.WriteLine(markdown);
        }

        // Non-zero exit if the system's own invariants are broken, so this is usable as a gate
        // in a pipeline rather than just as a document generator.
        outcome.AssertRowConservation();
        outcome.Reconciliation.AssertZeroDifferences();
        Console.Error.WriteLine(
            $"checksum={outcome.Checksum} rows_in={outcome.RowsIn} "
          + $"matched={outcome.RowsMatched} exceptions={outcome.RowsExcepted}");
    }

    /// <summary>Walks up to the folder holding <c>AQ.Denials.sln</c>, or null.</summary>
    public static string? FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "AQ.Denials.sln")))
                return directory.FullName;
            directory = directory.Parent;
        }
        return null;
    }

    /// <summary>The checked-in deliverable, when a repository root can be found.</summary>
    public static string DefaultOutputPath()
    {
        var root = FindRepositoryRoot() ?? Directory.GetCurrentDirectory();
        return Path.Combine(root, "docs", "PHASE1_RECONCILIATION.md");
    }

    public static string Render(IngestOutcome outcome)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Phase 1 — reconciliation report");
        sb.AppendLine();
        sb.AppendLine("> Generated by `dotnet run --project src/AQ.Denials.Api -- --report`.");
        sb.AppendLine("> Every figure below is computed by the ingestion pipeline; none is hand-typed.");
        sb.AppendLine();
        sb.AppendLine($"- **Full-state checksum:** `{outcome.Checksum}`");
        sb.AppendLine($"- **Rows in:** {outcome.RowsIn} = matched {outcome.RowsMatched} "
                    + $"+ exceptions {outcome.RowsExcepted} "
                    + $"({(outcome.RowsIn == outcome.RowsMatched + outcome.RowsExcepted ? "identity holds" : "IDENTITY BROKEN")})");
        sb.AppendLine();

        sb.AppendLine("## Row conservation, by source and entity");
        sb.AppendLine();
        sb.AppendLine("| Source | entity | input rows |");
        sb.AppendLine("|---|---|---|");
        foreach (var (entity, count) in outcome.RowsInByEntity.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            sb.AppendLine($"| see `SourceFile` | `{entity}` | {count} |");
        sb.AppendLine($"| **total** | | **{outcome.RowsIn}** |");
        sb.AppendLine();

        sb.AppendLine("## Exceptions by reason");
        sb.AppendLine();
        sb.AppendLine("| Reason code | rows |");
        sb.AppendLine("|---|---|");
        foreach (var (reason, count) in outcome.ExceptionCountsByReason)
            sb.AppendLine($"| `{reason}` | {count} |");
        sb.AppendLine($"| **total** | **{outcome.RowsExcepted}** |");
        sb.AppendLine();

        sb.AppendLine("## Exception detail");
        sb.AppendLine();
        sb.AppendLine("| Reason | Source | Claim | Explanation |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var e in outcome.Exceptions
                     .OrderBy(e => e.ReasonCode, StringComparer.Ordinal)
                     .ThenBy(e => e.SourceFile, StringComparer.Ordinal)
                     .ThenBy(e => e.ClaimId, StringComparer.Ordinal))
        {
            sb.Append("| `").Append(e.ReasonCode).Append("` | ")
              .Append(e.SourceFile).Append(" | ")
              .Append(e.ClaimId ?? "—").Append(" | ")
              .Append(Escape(e.Detail)).AppendLine(" |");
        }
        sb.AppendLine();

        sb.AppendLine(outcome.Reconciliation.ToMarkdown());

        sb.AppendLine("## Method notes");
        sb.AppendLine();
        sb.AppendLine("- Cash is measured from `BPR` at **transaction** level (one file carries 7–9 "
                    + "transaction sets, each with its own check date and often its own payer).");
        sb.AppendLine("- `Σ CLP04` counts **every** `CLP` in an imported file, including payment "
                    + "events whose claim is not in the export, so the two sides of the "
                    + "reconciliation describe the same population.");
        sb.AppendLine("- Adjustments are summed over the same population, and the portion that "
                    + "cannot be attributed to a claim is broken out rather than dropped.");
        sb.AppendLine("- The duplicate resend is retained, flagged, and contributes **$0.00** to cash.");
        sb.AppendLine("- Every monetary value is `decimal` with a fixed two-decimal scale; no "
                    + "floating point type appears anywhere in the money path.");

        return sb.ToString();
    }

    private static string Escape(string text) =>
        text.Replace("|", "\\|", StringComparison.Ordinal).Replace("\n", " ", StringComparison.Ordinal);
}
