// <auto-generated />
using System;
using AQ.Denials.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AQ.Denials.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007112441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AQ.Denials.Core.Domain.Adjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Carc")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int?>("ObservationServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("RemitObservationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObservationServiceId");

                    b.HasIndex("RemitObservationId");

                    b.ToTable("Adjustments");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("EntityKey")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("RunGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Adjudicated")
                        .HasColumnType("boolean");

                    b.Property<string>("AuthNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Charge")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CoderId")
                        .HasColumnType("text");

                    b.Property<string>("CurrentStatus")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Dos")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastCheckDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("LifetimePaid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PatientDob")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientFirst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientLast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrebillReviewed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RenderingNpi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RenderingProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SubmittedCharge")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SubmittedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.ClaimLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Charge")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Dx1")
                        .HasColumnType("text");

                    b.Property<string>("Dx2")
                        .HasColumnType("text");

                    b.Property<string>("Dx3")
                        .HasColumnType("text");

                    b.Property<string>("Dx4")
                        .HasColumnType("text");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer");

                    b.Property<string>("Modifier")
                        .HasColumnType("text");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimLines");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.ExceptionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IngestRunId")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalRef")
                        .HasColumnType("text");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("IngestRunId");

                    b.HasIndex("ReasonCode");

                    b.ToTable("ExceptionRows");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.IngestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FailureMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullStateChecksum")
                        .HasColumnType("text");

                    b.Property<int>("RowsExcepted")
                        .HasColumnType("integer");

                    b.Property<int>("RowsIn")
                        .HasColumnType("integer");

                    b.Property<int>("RowsMatched")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FullStateChecksum");

                    b.HasIndex("RunGuid")
                        .IsUnique();

                    b.ToTable("IngestRuns");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.ObservationService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Charge")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Paid")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RemarkCodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemitObservationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RemitObservationId");

                    b.ToTable("ObservationServices");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.RemitFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BprTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CheckDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ClaimCount")
                        .HasColumnType("integer");

                    b.Property<string>("DuplicateOfFileName")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TraceNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.HasIndex("PayloadSha256");

                    b.ToTable("RemitFiles");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.RemitObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PatientResponsibility")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RawClaimReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemarkCodes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemitFileId")
                        .HasColumnType("integer");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<decimal>("SubmittedCharge")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NaturalKey");

                    b.HasIndex("RemitFileId");

                    b.HasIndex("ClaimId", "Seq");

                    b.ToTable("RemitObservations");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.WorklogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmountAsLogged")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ClaimId")
                        .HasColumnType("text");

                    b.Property<bool>("DateAmbiguous")
                        .HasColumnType("boolean");

                    b.Property<string>("DateLoggedConservative")
                        .HasColumnType("text");

                    b.Property<string>("DateLoggedDmy")
                        .HasColumnType("text");

                    b.Property<string>("DateLoggedMdy")
                        .HasColumnType("text");

                    b.Property<string>("DateLoggedRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DateResolvedByFutureTest")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawClaimReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StatusRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RowNumber")
                        .IsUnique();

                    b.ToTable("WorklogEntries");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.Adjustment", b =>
                {
                    b.HasOne("AQ.Denials.Core.Domain.ObservationService", "Service")
                        .WithMany("Adjustments")
                        .HasForeignKey("ObservationServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AQ.Denials.Core.Domain.RemitObservation", "RemitObservation")
                        .WithMany("Adjustments")
                        .HasForeignKey("RemitObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemitObservation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.ClaimLine", b =>
                {
                    b.HasOne("AQ.Denials.Core.Domain.Claim", "Claim")
                        .WithMany("Lines")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.ExceptionRow", b =>
                {
                    b.HasOne("AQ.Denials.Core.Domain.IngestRun", "Run")
                        .WithMany()
                        .HasForeignKey("IngestRunId");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.ObservationService", b =>
                {
                    b.HasOne("AQ.Denials.Core.Domain.RemitObservation", "RemitObservation")
                        .WithMany("Services")
                        .HasForeignKey("RemitObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemitObservation");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.RemitObservation", b =>
                {
                    b.HasOne("AQ.Denials.Core.Domain.Claim", "Claim")
                        .WithMany("Observations")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AQ.Denials.Core.Domain.RemitFile", "RemitFile")
                        .WithMany("Observations")
                        .HasForeignKey("RemitFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("RemitFile");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.Claim", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.ObservationService", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.RemitFile", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("AQ.Denials.Core.Domain.RemitObservation", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
